#!/bin/sh

# gengames - utility to generate a test game and four users
# opens all users in your browser (defaults to firefox)
# $1 - Pass the URL of the site (works remotely) - default: localhost:8080

BROWSER="${BROWSER:-firefox}"
URL="${1:-localhost:8080}"

CREATE="http://$URL/create/game/E3F28830A6CC7D04EFA267773A5EB1F3ACC93BB17CC7A01318832AFC3E6F4F3C"

PIN=$(curl -Lv "$CREATE" 2>&1 \
	| grep -oE "Location: \S+" \
	| grep -Eo "[0-9]+")

HOST="http://$URL/play/host/$PIN"
JOIN="http://$URL/join?pin=$PIN&nick="

$BROWSER "$HOST" &
for nick in A B C D
do
	$BROWSER "$JOIN$nick" &
done
